"""Classify an IPv4 address against AWS's published EC2 ranges (CLO-538).

``orphaned_dns_record`` judges a Route 53 A record as orphaned only when its
IP is in the EC2 space of a known region. This module answers "which EC2
region, if any, owns this address?" from a pinned snapshot of
``ip-ranges.json`` (``aws_ip_ranges_snapshot``, regenerated by
``scripts/refresh_aws_ip_ranges.py``). Nothing is fetched at scan time.

Verdicts (``IpRangeClass.kind``):

* ``ec2``: in exactly one region's EC2 prefixes and in no other named
  service's prefix. ``region`` is that region.
* ``not_ec2``: outside every EC2 prefix. Either not AWS at all (Vercel,
  Cloudflare, on-prem) or AWS space that is not EC2 (CloudFront, Global
  Accelerator, API Gateway, ...). Never an orphaned Elastic IP or instance.
* ``ambiguous``: EC2 space that another named service also lists, or an EC2
  prefix with no single region (``GLOBAL``). Not judged.
* ``invalid``: not an IPv4 address.

A snapshot older than ``SNAPSHOT_MAX_AGE_DAYS`` (or one that cannot be read)
is not trusted: ``snapshot_is_fresh`` is False and the caller withholds.
"""

from __future__ import annotations

import ipaddress
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from functools import lru_cache
from typing import Dict, List, Optional, Tuple

SNAPSHOT_MAX_AGE_DAYS = 90

# A real region code (us-east-1, ap-southeast-4, us-gov-west-1, eu-isoe-west-1).
# ip-ranges.json also uses "GLOBAL", which names no region.
_REGION_RE = re.compile(r'^[a-z]{2}(?:-[a-z]+)+-\d+$')


@dataclass(frozen=True)
class IpRangeClass:
    kind: str  # 'ec2' | 'not_ec2' | 'ambiguous' | 'invalid'
    region: Optional[str] = None


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def snapshot_created_at() -> datetime:
    """``createDate`` of the pinned snapshot (format ``YYYY-MM-DD-hh-mm-ss``, UTC)."""
    from cloudwise_scan_core import aws_ip_ranges_snapshot as snap
    return datetime.strptime(snap.CREATE_DATE, '%Y-%m-%d-%H-%M-%S').replace(tzinfo=timezone.utc)


def snapshot_age_days(now: Optional[datetime] = None) -> float:
    now = now or _utcnow()
    return (now - snapshot_created_at()).total_seconds() / 86400.0


def snapshot_is_fresh(now: Optional[datetime] = None) -> bool:
    """True when the snapshot loads and is at most SNAPSHOT_MAX_AGE_DAYS old.
    Any failure to read it is False (MISSING), never an exception."""
    try:
        _index()
        return 0 <= snapshot_age_days(now) <= SNAPSHOT_MAX_AGE_DAYS
    except Exception:
        return False


# prefixlen -> {network int: region}. At most 33 lookups per address.
_Index = Tuple[Dict[int, Dict[int, str]], Dict[int, set]]


@lru_cache(maxsize=1)
def _index() -> _Index:
    from cloudwise_scan_core import aws_ip_ranges_snapshot as snap
    ec2: Dict[int, Dict[int, str]] = {}
    for cidr, region in snap.EC2_PREFIXES:
        net = ipaddress.IPv4Network(cidr)
        ec2.setdefault(net.prefixlen, {})[int(net.network_address)] = region
    ambiguous: Dict[int, set] = {}
    for cidr in snap.AMBIGUOUS_PREFIXES:
        net = ipaddress.IPv4Network(cidr)
        ambiguous.setdefault(net.prefixlen, set()).add(int(net.network_address))
    return ec2, ambiguous


def _matches(addr: int, prefixlen: int) -> int:
    """Network address (as int) of the /prefixlen containing ``addr``."""
    return int(ipaddress.IPv4Network((addr, prefixlen), strict=False).network_address)


def classify_ipv4(value: str) -> IpRangeClass:
    """Classify one A-record value. Raises nothing for bad input: a value
    that is not an IPv4 address is ``invalid``."""
    try:
        addr = int(ipaddress.IPv4Address(str(value).strip()))
    except (ipaddress.AddressValueError, ValueError):
        return IpRangeClass('invalid')
    ec2, ambiguous = _index()
    for prefixlen, nets in ambiguous.items():
        if _matches(addr, prefixlen) in nets:
            return IpRangeClass('ambiguous')
    regions: List[str] = []
    for prefixlen, nets in ec2.items():
        region = nets.get(_matches(addr, prefixlen))
        if region is not None:
            regions.append(region)
    if not regions:
        return IpRangeClass('not_ec2')
    distinct = set(regions)
    if len(distinct) != 1:
        return IpRangeClass('ambiguous')
    region = distinct.pop()
    if not _REGION_RE.match(region):
        return IpRangeClass('ambiguous')
    return IpRangeClass('ec2', region)
